<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ubl2-1\**\*.xsd" />
    <EmbeddedResource Include="ubl2-1\**\*.xsd" />
  </ItemGroup>

</Project>
